#!/usr/bin/perl -w
#
# $Id: sanitize_umlauts,v 1.1 2002-10-27 12:28:59 hjp Exp $
#

use strict;
use File::Find;


sub wanted {

    if (/[\204\224\201\216\231\232\341\202]/) {
	my $new = $_;
	$new =~ tr/\204\224\201\216\231\232\341\202/äöüÄÖÜßé/;
        print $File::Find::dir, ": $_ -> $new\n";
	rename $_, $new or die "cannot rename $_ to $new: $!";
    }
}



if (@ARGV == 0) { push (@ARGV, "."); }
finddepth(\&wanted, @ARGV);

print "\n\n";


# $Log: sanitize_umlauts,v $
# Revision 1.1  2002-10-27 12:28:59  hjp
# *** empty log message ***
#
