#!/usr/bin/perl -w
#
# $Id: sanitize_umlauts,v 1.2 2006-03-08 18:08:52 hjp Exp $
#

use strict;
use File::Find;


sub wanted {

    if (/[\204\224\201\216\231\232\202]/) {
	my $new = $_;
	$new =~ tr/\204\224\201\216\231\232\202/äöüÄÖÜé/;
        print $File::Find::dir, ": $_ -> $new\n";
	rename $_, $new or die "cannot rename $_ to $new: $!";
    }
}



if (@ARGV == 0) { push (@ARGV, "."); }
finddepth(\&wanted, @ARGV);

print "\n\n";


# $Log: sanitize_umlauts,v $
# Revision 1.2  2006-03-08 18:08:52  hjp
# Removed szlig conversion. Too dangerous as \341 is a valid character in
# latin-1, too.
#
# Revision 1.1  2002/10/27 12:28:59  hjp
# *** empty log message ***
#
