# $Id: GNUmakefile,v 1.2 2003-12-03 13:51:47 hjp Exp $

include GNUmakevars

clean:

install: $(SBINDIR)/mac-port $(SBINDIR)/list-mac-port

include GNUmakerules

# $Log: GNUmakefile,v $
# Revision 1.2  2003-12-03 13:51:47  hjp
# Added list-mac-port.
# bay-mac-port is obsolete, won't be installed any more.
#
# Revision 1.1  2001/04/11 14:31:28  hjp
# mac-port: convert mac address to switch port using snmp.
#
