# $Id: GNUmakefile,v 1.1 2001-04-11 14:31:28 hjp Exp $

include GNUmakevars

clean:

install: $(SBINDIR)/mac-port-bay $(SBINDIR)/mac-port

include GNUmakerules

# $Log: GNUmakefile,v $
# Revision 1.1  2001-04-11 14:31:28  hjp
# mac-port: convert mac address to switch port using snmp.
#
