#!/usr/bin/perl -w
#
# $Id: mac-port-bay,v 1.1 2001-04-11 14:31:29 hjp Exp $
#
# find the port of a baystack 350 T switch to which a given
# mac address is connected.
#
use strict;

sub usage {
    print STDERR "Usage: $0 mac-address\n";
    exit(1);
}


if (@ARGV != 1) {usage();}

my @hmac = split(/:/, $ARGV[0]);

my @dmac = map { hex } @hmac;

my $object = "17.4.3.1.2." . join(".", @dmac);

system("snmpget", "bay-switch-1", "public", $object);

# $Log: mac-port-bay,v $
# Revision 1.1  2001-04-11 14:31:29  hjp
# mac-port: convert mac address to switch port using snmp.
#
