#!/usr/bin/perl

$spooldir = "/usr/adm/motd";
$motdfile = "/etc/motd";

chdir $spooldir || die "cannot chdir to $spooldir";

# build a list of files in the spool directory
opendir DIR, "." || die "cannot open `.'";
@files = readdir (DIR);
closedir (DIR);

open MOTD, ">$motdfile" || die "cannot open $motdfile";

foreach $thisfile (@files) {
	if (-f $thisfile) {
		$nonempty=1;
		print MOTD "\n------------------------------------------------------------\n";
		open THISFILE, $thisfile || die "cannot open $thisfile";
		while ($line = <THISFILE>) {
			print MOTD $line;
		}
		close THISFILE;
	}
}
if ($nonempty) {
	print MOTD "\n------------------------------------------------------------\n";
}
system "/usr/local/bin/ci -l -q $motdfile" || die;
exit (0);
