.\" $Id: quotasanitycheck.8,v 1.1 1998-09-17 08:15:45 hjp Exp $
.\" $Log: quotasanitycheck.8,v $
.\" Revision 1.1  1998-09-17 08:15:45  hjp
.\" Added quotasanitycheck.8
.\" Changed BINDIR to SBINDIR in GNUmakefile and added MAN8DIR variable.
.\"
.\"
.TH quotasanitycheck 1
.SH NAME
quotasanitycheck - check user quotas for sanity
.SH SYNOPSIS
.B table
[
.B -b
.I blocks
] [
.B -f
.I files
] [
.B -F
.I factor
] 
.SH DESCRIPTION
This program performs some simple tests on quotas of all users and
reports the results. Currently these tests are:
.IP
The soft limit must be at least as high as specified by the 
.B \-b
or
.B \-f 
option (min)
.IP
The hard limit must be at least as high as the soft limit (softhard)
.IP
The difference between the hard limit and the current usage must not exceed the fraction of total free space specified by the 
.B \-F 
option (hardfree).
.SH EXAMPLES
.IP
.C quotasanitycheck -F 0.5
.PP
Checks that no user can fill up more than 50% of the available space.
.IP 
.C "quotasanitycheck -b 50000 -f 1000 -F 0.1"
.PP
Checks each user's soft limits are at least 50MB and 1000 files, and
that no user can fill up more than 10% of the available space.
.IP
.C "quotasanitycheck -b50000 -f1000 -F0.1 | grep FAIL | table -d' '"
.PP
As above, but prints only the users that fail at least one test and
formats the output nicely.
.SH AUTHOR
Peter Holzer (hjp@wsr.ac.at)
